import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import About from "./About";
import ContactMe from "./ContactMe";
import Hero from "./Hero";
import Projects from "./Projects";
import Skills from "./Skills";
import WorkExperience from "./WorkExperience";

const Home: NextPage = () => {
  return (
    //BGColor
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0 scroll-smooth">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/* Header */}
        <Header />
        {/* Hero */}
        <section id="hero" className="snap-start">
          <Hero />
        </section>
        {/* About */}
        <section id="about" className="snap-center">
          <About />
        </section>
        {/* Experience */}
        <section id="experience" className="snap-center">
          <WorkExperience />
        </section>
        {/* Skills */}
        <section id="skills" className="snap-start">
          <Skills />
        </section>
        {/* Projects */}
        <section id="projects" className="snap-start">
          <Projects />
        </section>
        {/* Contact Me */}
        <section id="contactme" className="snap-start">
          <ContactMe />
        </section>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
