import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import About from "./About";
import Hero from "./Hero";

const Home: NextPage = () => {
  return (
    //BGColor
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header */}
        <Header />
        {/* Hero */}
        <section id="hero" className="snap-center">
          <Hero />
        </section>
        {/* About */}
        <section>
          <About />
        </section>
        {/* Experience */}
        {/* Skills */}
        {/* Projects */}
        {/* Contact Me */}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
